package:
  name: pyocct
  version: "7.4.0.0"

source:
  path: ../..

build:
  number: 0
  features:
    - vc14 # [win and py35]
    - vc14 # [win and py36]

requirements:
  build:
    - python
    - vc 14 # [win]
    - cmake
    - ninja
    - occt ==7.4.0
    - tbb-devel
    - smesh ==8.3.0.3

  run:
    - python
    - wxpython
    - vc 14 # [win]
    - occt ==7.4.0
    - smesh ==8.3.0.3

test:
  source_files:
    - test

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
