version: 7.3.0.0.{build}

image: Visual Studio 2015

environment:
  matrix:
    - CONDA_INSTALL_LOCN: C:\Miniconda35-x64
      TARGET_ARCH: x64
      ARCH: 64
    - CONDA_INSTALL_LOCN: C:\Miniconda36-x64
      TARGET_ARCH: x64
      ARCH: 64

platform:
  - x64

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - cmd: conda.exe install conda-build --yes
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: conda.exe config --add channels conda-forge
  - cmd: git clone https://github.com/pybind/pybind11.git pybind11

build: off

test_script:
  - cmd: conda.exe build ci\conda
  - cmd: mkdir dist
  - cmd: copy %CONDA_INSTALL_LOCN%\conda-bld\win-%ARCH%\pyocct*.bz2 dist

artifacts:
- path: dist\*
