jobs:
  - template: conda-build.yml
    parameters:
      name: 'Windows_VS2017_py36'
      vmImage: 'vs2017-win2016'
      python: '3.6'

  - template: conda-build.yml
    parameters:
      name: 'Windows_VS2017_py37'
      vmImage: 'vs2017-win2016'
      python: '3.7'
