parameters:
  name: 'Windows_VS2017_py36'
  vmImage: 'vs2017-win2016'
  python: '3.6'

jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 360
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:

    # Ubuntu install OpenGL items
    - ${{ if contains(parameters.vmImage, 'ubuntu') }}:
      - bash: |
          sudo apt-get update && \
          sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev libglfw3-dev libgles2-mesa-dev
        displayName: 'Install OpenGL headers'

    # add conda to the path
    - ${{ if or(contains(parameters.vmImage, 'macOS'),contains(parameters.vmImage, 'ubuntu')) }}:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: 'Add conda to PATH'
    - ${{ if contains(parameters.vmImage, 'win') }}:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: 'Add conda to PATH'

    # clone binder
    - bash: |
        git clone https://github.com/LaughlinResearch/pyOCCT_binder.git binder
      displayName: 'Clone binder'

    # configure conda and build
    - bash: |
        conda info -a && \
        conda config --add channels conda-forge
      displayName: 'Configure conda'

    # create conda environment
    - bash: |
        conda create --yes --quiet --name pyOCCT \
            python=${{ parameters.python }} conda-build
      displayName: 'Create conda environment'

    # run conda build
    - bash: |
        source activate pyOCCT && \
        mkdir conda && \
        conda build  ci/conda --no-remove-work-dir --dirty --output-folder conda
      displayName: 'Run conda build'
      env:
         PYBIND11_PYTHON_VERSION: '${{ parameters.python }}'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: './conda'
        artifactName: 'pyocct-${{ parameters.python }}-${{ parameters.vmImage }}'
