parameters:
  name: 'Windows_VS2017_py36'
  vmImage: 'vs2017-win2016'
  python: '3.6'

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:

    # Ubuntu install OpenGL items
    - ${{ if contains(parameters.vmImage, 'ubuntu') }}:
      - bash: |
          sudo apt-get update && \
          sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev
        displayName: 'Install OpenGL headers'

    # add conda to the path
    - ${{ if or(contains(parameters.vmImage, 'macOS'),contains(parameters.vmImage, 'ubuntu')) }}:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: 'Add conda to PATH'
    - ${{ if contains(parameters.vmImage, 'win') }}:
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: 'Add conda to PATH'

    # clone pybind11
    - bash: |
        git clone https://github.com/pybind/pybind11.git pybind11
      displayName: 'Clone pybind11'

    # configure conda and build
    - bash: |
        conda info -a && \
        conda config --add channels conda-forge
      displayName: 'Configure conda'

    - bash: |
        conda create --yes --quiet --name pyOCCT python=${{ parameters.python }} conda-build
      displayName: 'Create conda environment'

    - bash: |
        source activate pyOCCT && \
        conda build  ci/conda
      displayName: 'Run conda build'
