name: Conda Package
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:

      - name: "Install OpenGL"
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev libglfw3-dev libgles2-mesa-dev

      - name: "Clone pyOCCT"
        uses: actions/checkout@v2

      - name: "Clone binder"
        shell: bash -l {0}
        run: |
            git clone https://github.com/LaughlinResearch/pyOCCT_binder.git binder

      - name: "Configure conda"
        shell: bash -l {0}
        run: |
            conda config --add channels conda-forge
            conda install conda-build

      - name: "Check conda"
        shell: bash -l {0}
        run: |
            conda info
            conda list

      - name: "Run conda build"
        shell: bash -l {0}
        run: |
            mkdir conda
            conda build  ci/conda --python ${{ matrix.python-version }} --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v1
        with:
            name: pyocct-py${{ matrix.python-version }}-(${{ matrix.os }})
            path: conda
