name: Conda Package
on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.6', '3.7']
    steps:

      - name: "Install OpenGL"
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev libglfw3-dev libgles2-mesa-dev

      - name: "Clone pyOCCT"
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: "Add conda to PATH"
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          echo "::add-path::$CONDA/Scripts"

      - name: "Configure conda"
        shell: bash -l {0}
        run: |
          conda env create -f environment.yml

      - name: "Check conda"
        shell: bash -l {0}
        run: |
          conda init bash
          conda activate pyOCCT && \
          conda info -a && \
          conda list

      - name: "Generate bindings"
        shell: bash -l {0}
        run: |
          conda init bash
          conda activate pyOCCT && \
          python binder/run.py -c binder/config.txt -o src/occt

      - name: "Run conda build"
        shell: bash -l {0}
        run: |
          mkdir conda
          conda init bash
          conda activate pyOCCT && \
          conda build  ci/conda --python ${{ matrix.python-version }} --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v1
        with:
          name: pyocct-py${{ matrix.python-version }}_${{ matrix.os }}
          path: conda
