name: Conda Package
on:
  push:
    branches:
    - 'review/*'
  pull_request:
    branches:
    - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        python-version: ['3.6']
    steps:
      - name: "Clone pyOCCT"
        uses: actions/checkout@v2

      - name: "Install miniconda"
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: "Install OpenGL"
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt-get update
            sudo apt-get -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev libglfw3-dev libgles2-mesa-dev

      - name: "Configure conda"
        run: |
            conda info
            conda config --add channels conda-forge

      - name: "Install conda build"
        run: |
            conda install python=${{ matrix.python-version }} conda-build=3.16.3

      - name: "Clone binder"
        shell: bash -l {0}
        run: |
            git clone https://github.com/LaughlinResearch/pyOCCT_binder.git binder

      - name: "Build"
        shell: bash -l {0}
        run: |
            mkdir conda
            conda build  ci/conda --output-folder conda

      - name: "Upload conda package"
        uses: actions/upload-artifact@v1
        with:
            name: pyocct-py${{ matrix.python-version }}-(${{ matrix.os }})
            path: conda
